# environment.yml
# Use this file to create your conda environment
# Run: conda env create -f environment.yml
name: voice-auth
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit=11.3  # Adjust based on your GPU
  - pip
  - pip:
    - librosa
    - matplotlib
    - pandas
    - scikit-learn
    - tqdm
    - captum
    - deepfilternet
    - pysoundfile
    - tensorboard
    - sox
