# environment-mac.yml
# Use this file to create your conda environment on Mac
# Run: conda env create -f environment-mac.yml
name: voice-auth-mac
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchaudio
  - torchvision
  - pip
  - librosa
  - matplotlib
  - pandas
  - scikit-learn
  - scipy
  - tqdm
  - numba
  - pip:
    - captum
    - deepfilternet
    - pysoundfile
    - tensorboard
    - sox
