# -*- coding: utf-8 -*-
"""final_sincnet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ei07TFT5a134vb__7FaNxOPLkWeMmM7S
"""

import os
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Set paths - adjust according to your project structure
os.environ['DATASET_PATH'] = "/content/drive/Shareddrives/VoxCeleb1/Dev_Filtered/wav"
os.environ['TEST_PATH'] = "/content/drive/Shareddrives/VoxCeleb1/Test_Filtered/wav"
os.environ['OUTPUT_PATH'] = "/content/drive/Shareddrives/VoxCeleb1/SincNet/Features"
os.makedirs(os.getenv('OUTPUT_PATH'), exist_ok=True)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/Shareddrives/VoxCeleb1/SincNet/

!python run_sincnet_updated.py --dataset_path $DATASET_PATH --output_path $OUTPUT_PATH --tune_model